#!/bin/sh
# emacs -- Override 'emacs' to launch the GUI version of emacs

# Mike Barker <mike@thebarkers.com>
# October 21, 2014

# Copyright (c) 2014 Mike Barker

# Change log:
# 2014.10.21
# * First release.

/Applications/Emacs.app/Contents/MacOS/Emacs "$@"
